project: https://github.com/qualcomm/resource-tuner

branches:
  main:
    modes:
      non-blocking:
        headers:
          - client/APIs/Include/UrmAPIs.h
          - modula/Common/Include/Common.h
          - resource-tuner/extensions/Include/Extensions.h
