# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

InitConfigs:
  - CgroupsInfo:
    - Name: "init.scope"
      Create: false
      ID: 1
    - Name: "system.slice"
      Create: false
      ID: 2
    - Name: "user.slice"
      Create: false
      ID: 3
    - Name: "focused-cgroup"
      Create: false
      ID: 4
