name: Build Resource Tuner

on:
  workflow_dispatch:
  pull_request_target: # requiring access to base repo
    types: [opened, synchronize, reopened]
    branches:
      - main
    # paths-ignore: #update if something has to be ignored.

jobs:
  build:
    runs-on:
      group: GHA-CSEPerf-prd-SelfHosted-RG
      labels: [self-hosted, cseperf-prd-u2204-arm64-xlrg-od-ephem]

    steps:
      - uses: actions/checkout@v5
        with:
          repository: qualcomm/urm-image
          token: ${{ secrets.MY_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build URM image (from Git URL) and load locally
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: urm-image:ci
          load: true
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sync codebase
        uses: qualcomm/resource-tuner/.github/actions/sync@main
        with:
          event_name: ${{ github.event_name }}
          pr_ref: ${{ github.event.pull_request.head.ref }}
          pr_repo: ${{ github.event.pull_request.head.repo.full_name }}
          base_ref: ${{ github.ref_name }}

      - name: Build resource-tuner in the URM container
        run: |
          docker run --rm -v "$PWD":/workspace -w /workspace urm-image:ci bash -lc '
            set -euo pipefail
            mkdir build
            cd build
            cmake .. -DBUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=./resource-tuner-bins/usr/
            cmake --build .
            make install
            mkdir -p resource-tuner-bins/etc/urm/{common,custom,tests}
            mkdir -p resource-tuner-bins/etc/urm/tests/{configs,nodes}
            cp ../configs/*.yaml resource-tuner-bins/etc/urm/common/
            cp ../resource-tuner/tests/Configs/*.yaml resource-tuner-bins/etc/urm/tests/configs/
            cp ../resource-tuner/tests/Configs/ResourceSysFsNodes/*.txt resource-tuner-bins/etc/urm/tests/nodes/
          '
      - name: Create a tar file of build
        run: |
          cd build
          tar -cjf "${{ github.workspace }}/resource-tuner-bins.tar.gz" resource-tuner-bins
          cd ${{ github.workspace }}
          touch file_list.txt
          echo "${{ github.workspace }}/resource-tuner-bins.tar.gz" >> file_list.txt

      - name: Upload artifacts to S3
        uses: qualcomm/resource-tuner/.github/actions/aws_s3_helper@main
        with:
          s3_bucket: qli-prd-cseperf-gh-artifacts
          mode: multi-upload
          local_file: file_list.txt
